name: PR Performance check

on: [pull_request]

jobs:
  runBenchmark:
    name: Criterion Compare PRs
    runs-on: [self-hosted, benchmark]
    steps:
      - uses: actions/checkout@v2
      - name: Check Against trunk
        uses: boa-dev/criterion-compare-action@v2.0.0
        with:
          benchName: "solve n=100"
          branchName: "${{github.base_ref}}"
          token: ${{ secrets.GITHUB_TOKEN }}