name: PR Performance check

on: [pull_request]

jobs:
  runBenchmark:
    name: Criterion Compare PRs
    runs-on: [self-hosted, benchmark]
    steps:
      - name: Clean Up Runner
        uses: AutoModality/action-clean@v1
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with: 
          rust-version: stable
          components: clippy
      - uses: actions/checkout@v2
      - name: Check Against trunk
        uses: chipbuster/criterion-compare-action@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branchName: trunk
