name: PR Performance check

on: [pull_request]

jobs:
  runBenchmark:
    name: Criterion Compare PRs
    runs-on: [self-hosted, benchmark]
    steps:
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - uses: actions/checkout@v2
      - name: Check Perf With Critcmp
        uses: chipbuster/criterion-compare@devel
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workDir: "./subdir"